package UI;

import BLL.Client;
import BLL.ClientRegister;
import BLL.Project;
import BLL.ProjectRegister;
import BLL.Region;
import BLL.Staff;
import BLL.Worker;
import java.awt.Color;
import java.awt.Dimension;
import java.beans.PropertyVetoException;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.event.CaretEvent;
import javax.swing.event.CaretListener;
import javax.swing.text.DateFormatter;
import javax.swing.text.MaskFormatter;

/**
 * Creates new media projects
 * 
 * @author James Staite
 * @version 1.0.0
 */
public class CreateProjectUI extends javax.swing.JInternalFrame {

    // Reference to user from Main UI
    private Staff manager;
    
    /**
     * Creates new form CreateProjectUI
     */
    public CreateProjectUI(Worker user) {
        super("Create New Project Details",false,true,false,false);
        initComponents();
        
        // set default button
        this.getRootPane().setDefaultButton(btnDefineTeam);
        
        // load region combox with region information
        DefaultComboBoxModel regionComboModel = new DefaultComboBoxModel();
        for(Region region: Region.values())
        {
            regionComboModel.addElement(region);
        }
        cmbRegion.setModel(regionComboModel);
        
        // load client combox with client details
        DefaultComboBoxModel clientComboModel = new DefaultComboBoxModel();
        
        ClientRegister clientReg = ClientRegister.getInstance();
        for(Client client: clientReg.getClientList())
        {
            clientComboModel.addElement(client);
        }
        cmbClient.setModel(clientComboModel);
        
        // Set default date tomorrow
        Date today = new Date();        
        Date date = new Date(today.getTime() + (1000 * 60 * 60 * 24));
        ftxtCompletionDate.setValue(date);
        
        // set Managers Details
        txtManager.setText(user.getName());
        manager = (Staff)user;
        
        // setup validation events for required fields
        txtProjectName.addCaretListener(new CaretListener() 
        {
            @Override
            public void caretUpdate(CaretEvent e) 
            {
                CreateProjectUI.this.validiateForm();
            }
        });
        
        txtDiscTitle.addCaretListener(new CaretListener() 
        {
            @Override
            public void caretUpdate(CaretEvent e) 
            {
                CreateProjectUI.this.validiateForm();
            }
        });
        
        ftxtCompletionDate.addCaretListener(new CaretListener() 
        {
            @Override
            public void caretUpdate(CaretEvent e) 
            {
                CreateProjectUI.this.validiateForm();
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblProjectName = new javax.swing.JLabel();
        txtProjectName = new javax.swing.JTextField();
        lblDiscTitle = new javax.swing.JLabel();
        txtDiscTitle = new javax.swing.JTextField();
        lblDiscRegion = new javax.swing.JLabel();
        btnCreateProject = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        btnDefineTeam = new javax.swing.JButton();
        cmbRegion = new javax.swing.JComboBox();
        DateFormat format = new SimpleDateFormat("dd/MM/yyyy");
        DateFormatter df = new DateFormatter(format);
        ftxtCompletionDate = new javax.swing.JFormattedTextField(df);
        lblCompletionDate = new javax.swing.JLabel();
        lblManager = new javax.swing.JLabel();
        txtManager = new javax.swing.JTextField();
        lblClient = new javax.swing.JLabel();
        cmbClient = new javax.swing.JComboBox();

        setTitle("Create Project");

        lblProjectName.setText("Project Name");

        lblDiscTitle.setText("Disc Title");

        lblDiscRegion.setText("Disc Region");

        btnCreateProject.setText("Create Project");
        btnCreateProject.setEnabled(false);
        btnCreateProject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateProjectActionPerformed(evt);
            }
        });

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        btnDefineTeam.setText("Define Project Team");
        btnDefineTeam.setEnabled(false);
        btnDefineTeam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDefineTeamActionPerformed(evt);
            }
        });

        cmbRegion.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        try
        {
            MaskFormatter dateMask = new MaskFormatter("##/##/####");
            dateMask.install(ftxtCompletionDate);
        } catch (ParseException ex)
        {
            Logger.getLogger(CreateProjectUI.class.getName()).log(Level.SEVERE, null, ex);
        }

        lblCompletionDate.setText("Completion Date");

        lblManager.setText("Manager");

        txtManager.setEditable(false);
        txtManager.setEnabled(false);

        lblClient.setText("Client");

        cmbClient.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 195, Short.MAX_VALUE)
                        .addComponent(btnCancel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDefineTeam)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCreateProject))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblProjectName)
                            .addComponent(lblDiscTitle)
                            .addComponent(lblDiscRegion)
                            .addComponent(lblCompletionDate)
                            .addComponent(lblManager)
                            .addComponent(lblClient))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtProjectName)
                            .addComponent(txtDiscTitle)
                            .addComponent(txtManager)
                            .addComponent(cmbRegion, 0, 277, Short.MAX_VALUE)
                            .addComponent(ftxtCompletionDate, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbClient, 0, 407, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblClient)
                    .addComponent(cmbClient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblProjectName)
                    .addComponent(txtProjectName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDiscTitle)
                    .addComponent(txtDiscTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbRegion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDiscRegion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ftxtCompletionDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCompletionDate))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblManager)
                    .addComponent(txtManager, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCreateProject)
                    .addComponent(btnCancel)
                    .addComponent(btnDefineTeam))
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // close form
        try {
            this.setClosed(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(CreateClientUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnDefineTeamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDefineTeamActionPerformed
        // get reference to client register
        ProjectRegister projectReg = ProjectRegister.getInstance();

        // check if the project already exists
        if(projectReg.findbyName(txtProjectName.getText()) == null)
        {
            txtProjectName.setBackground(UIManager.getColor( "Panel.background"));
            // Warn user that the project will be created
            int answer = JOptionPane.showConfirmDialog(this, "Before you can define the project team the\nproject must be created, confirm you wish to create the project.","Information",JOptionPane.OK_CANCEL_OPTION);

            if (answer == JOptionPane.YES_OPTION) 
            {
                // create new client
                Project project = projectReg.addProject(txtProjectName.getText(), txtDiscTitle.getText(), (Client)cmbClient.getSelectedItem(), (Region)cmbRegion.getSelectedItem(), manager, (Date)ftxtCompletionDate.getValue());

                // create Define Project Team Form
                DefineTeamUI frm = new DefineTeamUI(project);
                this.getDesktopPane().add(frm);
                Dimension desktopSize = getDesktopPane().getSize();
                Dimension jInternalFrameSize = frm.getSize();
                frm.setLocation((desktopSize.width - jInternalFrameSize.width)/2,(desktopSize.height- jInternalFrameSize.height)/2);
                frm.setVisible(true);
                // close form
                try {
                    this.setClosed(true);
                } catch (PropertyVetoException ex) {
                    Logger.getLogger(CreateClientUI.class.getName()).log(Level.SEVERE, null, ex);
                }  
            }
        }
        else
        {        
            txtProjectName.setBackground(Color.YELLOW);
            JOptionPane.showMessageDialog(this, "A project with this name already exists. \nUnable to create this project again","Information",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnDefineTeamActionPerformed

    private void btnCreateProjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateProjectActionPerformed
        // get reference to client register
        ProjectRegister projectReg = ProjectRegister.getInstance();

        // create new client
        Project created = projectReg.addProject(txtProjectName.getText(), txtDiscTitle.getText(), (Client)cmbClient.getSelectedItem(), (Region)cmbRegion.getSelectedItem(), manager, (Date)ftxtCompletionDate.getValue());

        if (created == null)
        {
            txtProjectName.setBackground(Color.YELLOW);
            JOptionPane.showMessageDialog(this, "A project with this name already exists. \nUnable to create this project again","Information",JOptionPane.ERROR_MESSAGE);
        }
        else
        {
            // close form
            txtProjectName.setBackground(UIManager.getColor( "Panel.background"));
            JOptionPane.showMessageDialog(this, "Project has been created","Information",JOptionPane.INFORMATION_MESSAGE);
            try {
                this.setClosed(true);
            } catch (PropertyVetoException ex) {
                Logger.getLogger(CreateClientUI.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnCreateProjectActionPerformed

    private void validiateForm()
    {
        boolean invalid = false;
        
        // check project name entered
        if (txtProjectName.getText().length() == 0)
        {
             invalid = true;
        } 
        
        // check disc title entered
        if (txtDiscTitle.getText().length() == 0)
        {
            invalid = true;
        }
        
        // check date is after today
        Date date = (Date)ftxtCompletionDate.getValue();
        if (!date.after(Calendar.getInstance().getTime()))
        {
            invalid = true;
        }
        
        if (invalid)
        {
            btnCreateProject.setEnabled(false);
            btnDefineTeam.setEnabled(false);
        }
        else
        {
            btnCreateProject.setEnabled(true);
            btnDefineTeam.setEnabled(true);
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnCreateProject;
    private javax.swing.JButton btnDefineTeam;
    private javax.swing.JComboBox cmbClient;
    private javax.swing.JComboBox cmbRegion;
    private javax.swing.JFormattedTextField ftxtCompletionDate;
    private javax.swing.JLabel lblClient;
    private javax.swing.JLabel lblCompletionDate;
    private javax.swing.JLabel lblDiscRegion;
    private javax.swing.JLabel lblDiscTitle;
    private javax.swing.JLabel lblManager;
    private javax.swing.JLabel lblProjectName;
    private javax.swing.JTextField txtDiscTitle;
    private javax.swing.JTextField txtManager;
    private javax.swing.JTextField txtProjectName;
    // End of variables declaration//GEN-END:variables
}
